Models/ErrorViewModel.cs
using System;

namespace ProjectMohan.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Nouvelle.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectMohan.Models
{
    public class Nouvelle
    {
        public int ID { get; set; }
        public string Titre { get; set; }
        public string Text { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjectMohan.Models;

namespace ProjectMohan.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NouvellesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjectMohan.BD;
using ProjectMohan.ViewModel.Nouvelles;

namespace ProjectMohan.Controllers
{
    public class NouvellesController : Controller
    {
        // GET: Nouvelle

        DAL dal = new DAL();
        public ActionResult Index()
        {
            IndexViewModel viewModel = new IndexViewModel();

            viewModel.nouvelle = dal.GetNouvelles();
            return View(viewModel);
        }

        // GET: Nouvelle/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Nouvelle/Create
        public ActionResult Create()
        {
            //CreateEditeNouvelleViewModel viewmodel = new CreateEditeNouvelleViewModel();
            //viewmodel.Action = "Create";
            //return View("CreateEditeNouvelle",viewmodel);
            string embed = "<object data=\"{0}\" type=\"application/pdf\" width=\"500px\" height=\"300px\">";
            embed += "If you are unable to view file, you can download from <a href = \"{0}\">here</a>";
            embed += " or download <a target = \"_blank\" href = \"http://get.adobe.com/reader/\">Adobe PDF Reader</a> to view the file.";
            embed += "</object>";
            TempData["Embed"] = string.Format(embed, "~/pdf/test.pdf");

            return View("CreateEditeNouvelle");
        }

        // POST: Nouvelle/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {

            try
            {
                dal.AjouterNouvelle(Request.Form["Titre"], Request.Form["Texte"]);
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Nouvelle/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Nouvelle/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Nouvelle/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Nouvelle/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Nouvelles/CreateEditeNouvelle.cshtml
@*@model ProjectMohan.ViewModel.Nouvelles.CreateEditeNouvelleViewModel

    @{
        ViewData["Title"] = "View";
    }

    <h1>View</h1>

    <h4>Crée une nouvelles</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <form asp-action="@Model.Action">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Titre" class="control-label"></label>
                    <input asp-for="Titre" class="form-control" />
                    <span asp-validation-for="Titre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Text" class="control-label"></label>
                    <textarea asp-for="Text"  TextMode="multiline" rows="50" class="form-control"></textarea>
                    <span asp-validation-for="Text" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }*@

@{
    Layout = null;
}

<meta name="viewport" content="width=device-width" />
<style type="text/css">
    body {
        font-family: Arial;
        font-size: 10pt;
    }
</style>
@using (Html.BeginForm("ViewPDF", "Home", FormMethod.Post))
{
    <a href="javascript:;" onclick="document.forms[0].submit();">View PDF</a>
    <hr />
    @Html.Raw(TempData["Embed"])
}

Views/Nouvelles/Index.cshtml
@using ProjectMohan.ViewModel.Nouvelles
@model IndexViewModel

    @{
        ViewData["Title"] = "Index";
    }

    <h1>Index</h1>

    <p>
        <a asp-action="Create" ><button class="btn btn-primary">Ajouter une Nouvelle</button></a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    Titre
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.nouvelle)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Titre)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
            }
        </tbody>
    </table>

Views/Nouvelles/View.cshtml
@model ProjectMohan.ViewModel.Nouvelles.CreateEditeNouvelleViewModel

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>CreateEditeNouvelleViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titre" class="control-label"></label>
                <input asp-for="Titre" class="form-control" />
                <span asp-validation-for="Titre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectMohan</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectMohan</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nouvelles" asp-action="Index">Nouvelle</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ProjectMohan - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>